VirtoCommerce/vc-module-elastic-search

VirtoCommerce.ElasticSearchModule.Data/ElasticSearchProvider.cs, VirtoCommerce.ElasticSearchModule.Data/ElasticSearchRequestBuilder.cs, VirtoCommerce.ElasticSearchModule.Web/Module.cs
Allow injecting ElasticClient to enforce custom connection rules like logging and security.
=> Allow extending ElasticSearchProvider

VirtoCommerce.ElasticSearchModule.Web/Module.cs
#137 vc-module-core: Fixed DI registration by specifying injected type;
=> #137 vc-module-core: Fixed DI registration by specifying injected type;

src/VirtoCommerce.ElasticSearchModule.Data/ElasticSearchProvider.cs, src/VirtoCommerce.ElasticSearchModule.Data/ElasticSearchRequestBuilder.cs, src/VirtoCommerce.ElasticSearchModule.Data/ElasticSearchResponseBuilder.cs, src/VirtoCommerce.ElasticSearchModule.Data/VirtoCommerce.ElasticSearchModule.Data.csproj, tests/VirtoCommerce.ElasticSearchModule.Tests/VirtoCommerce.ElasticSearchModule.Tests.csproj
This changes
https://github.com/VirtoCommerce/vc-module-elastic-search/compare/6271051b6d74ba67f4129dafad58d165028ff637...da0686e30b7488458d900b7ca8a712b20fd54627
=> Actualization v3 with v2 changes

VirtoCommerce.ElasticSearchModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VP-3109
=> VP-3109: Fix logo

src/VirtoCommerce.ElasticSearchModule.Data/ElasticSearchRequestBuilder.cs
VP-5985 Sort by scoring relevance and test all sorting scenarios
Add sorting by relevance
=> VP-5985: Add sort by scoring relevance

src/VirtoCommerce.ElasticSearchModule.Data/VirtoCommerce.ElasticSearchModule.Data.csproj, src/VirtoCommerce.ElasticSearchModule.Web/Module.cs, src/VirtoCommerce.ElasticSearchModule.Web/VirtoCommerce.ElasticSearchModule.Web.csproj, src/VirtoCommerce.ElasticSearchModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VP-6905
=> VP-6905 extend module with IHasConfiguration

src/VirtoCommerce.ElasticSearchModule.Data/VirtoCommerce.ElasticSearchModule.Data.csproj, src/VirtoCommerce.ElasticSearchModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/PT-207
=> PT-207: Enable Source link support

src/VirtoCommerce.ElasticSearchModule.Data/ElasticSearchProvider.cs, src/VirtoCommerce.ElasticSearchModule.Data/VirtoCommerce.ElasticSearchModule.Data.csproj, src/VirtoCommerce.ElasticSearchModule.Web/VirtoCommerce.ElasticSearchModule.Web.csproj, tests/VirtoCommerce.ElasticSearchModule.Tests/VirtoCommerce.ElasticSearchModule.Tests.csproj
Create filed mappings based on IndexDocumentFieldValueType, not on field value.
=> PT-2650 Add mapping by Document Field value type

src/VirtoCommerce.ElasticSearchModule.Data/VirtoCommerce.ElasticSearchModule.Data.csproj, src/VirtoCommerce.ElasticSearchModule.Web/VirtoCommerce.ElasticSearchModule.Web.csproj, tests/VirtoCommerce.ElasticSearchModule.Tests/VirtoCommerce.ElasticSearchModule.Tests.csproj
Added SonarQubeTestProject property to csproj files
=> VCI-134: Fix project contains only TEST-code issue

.github/workflows/main.yml, .github/workflows/publish_nugets.yml, Directory.Build.props, src/VirtoCommerce.ElasticSearchModule.Data/VirtoCommerce.ElasticSearchModule.Data.csproj, src/VirtoCommerce.ElasticSearchModule.Web/VirtoCommerce.ElasticSearchModule.Web.csproj, src/VirtoCommerce.ElasticSearchModule.Web/module.manifest, tests/VirtoCommerce.ElasticSearchModule.Tests/VirtoCommerce.ElasticSearchModule.Tests.csproj
Bump .Net and EF up to 6
https://virtocommerce.atlassian.net/browse/PT-1956
=> PT-1956: Bump .Net and EF up to 6

src/VirtoCommerce.ElasticSearchModule.Data/ElasticSearchProvider.cs, src/VirtoCommerce.ElasticSearchModule.Data/VirtoCommerce.ElasticSearchModule.Data.csproj, src/VirtoCommerce.ElasticSearchModule.Web/VirtoCommerce.ElasticSearchModule.Web.csproj, src/VirtoCommerce.ElasticSearchModule.Web/module.manifest, tests/VirtoCommerce.ElasticSearchModule.Tests/VirtoCommerce.ElasticSearchModule.Tests.csproj
https://virtocommerce.atlassian.net/browse/PT-6520
=> PT-6520: Add Blue-Green implementation

src/VirtoCommerce.ElasticSearchModule.Data/ElasticSearchProvider.cs, src/VirtoCommerce.ElasticSearchModule.Data/IndexationParameters.cs, src/VirtoCommerce.ElasticSearchModule.Data/IndexingParameters.cs, src/VirtoCommerce.ElasticSearchModule.Data/VirtoCommerce.ElasticSearchModule.Data.csproj, src/VirtoCommerce.ElasticSearchModule.Web/VirtoCommerce.ElasticSearchModule.Web.csproj, src/VirtoCommerce.ElasticSearchModule.Web/module.manifest, tests/VirtoCommerce.ElasticSearchModule.Tests/SearchProviderTests.cs, tests/VirtoCommerce.ElasticSearchModule.Tests/VirtoCommerce.ElasticSearchModule.Tests.csproj
https://virtocommerce.atlassian.net/browse/PT-6878
=> PT-6878: Refactoring blue green and partial update to prevent breaking changes

src/VirtoCommerce.ElasticSearchModule.Data/ElasticSearchRequestBuilder.cs
https://virtocommerce.atlassian.net/browse/PT-4367
=> PT-4367: pass filter into Range aggregation

VirtoCommerce.ElasticSearchModule.sln.DotSettings, src/VirtoCommerce.ElasticSearchModule.Data/ElasticSearchClient.cs, src/VirtoCommerce.ElasticSearchModule.Data/ElasticSearchConnectionSettings.cs, src/VirtoCommerce.ElasticSearchModule.Data/ElasticSearchProvider.cs, src/VirtoCommerce.ElasticSearchModule.Data/Extensions/PropertyExtensions.cs, src/VirtoCommerce.ElasticSearchModule.Web/Module.cs, src/VirtoCommerce.ElasticSearchModule.Web/ModuleConstants.cs, tests/VirtoCommerce.ElasticSearchModule.Tests/ElasticSearchRequestBuilderTests.cs, tests/VirtoCommerce.ElasticSearchModule.Tests/ElasticSearchTests.cs, tests/VirtoCommerce.ElasticSearchModule.Tests/SearchProviderTestsBase.cs, tests/VirtoCommerce.ElasticSearchModule.Tests/VirtoCommerce.ElasticSearchModule.Tests.csproj
Fix extensibility bugs, fix crashes on creating new indexes.
https://virtocommerce.atlassian.net/browse/PT-9076
=> PT-9076: Fix extensibility bugs

src/VirtoCommerce.ElasticSearchModule.Data/ElasticSearchProvider.cs, src/VirtoCommerce.ElasticSearchModule.Data/VirtoCommerce.ElasticSearchModule.Data.csproj, src/VirtoCommerce.ElasticSearchModule.Web/VirtoCommerce.ElasticSearchModule.Web.csproj, src/VirtoCommerce.ElasticSearchModule.Web/module.manifest, tests/VirtoCommerce.ElasticSearchModule.Tests/VirtoCommerce.ElasticSearchModule.Tests.csproj
https://virtocommerce.atlassian.net/browse/PT-10227
=> PT-10227: set separate scopes for different document types

src/VirtoCommerce.ElasticSearchModule.Data/ElasticSearchProvider.cs, src/VirtoCommerce.ElasticSearchModule.Web/Localizations/en.VirtoCommerce.ElasticSearch.json, src/VirtoCommerce.ElasticSearchModule.Web/ModuleConstants.cs
https://virtocommerce.atlassian.net/browse/PT-10801
=> PT-10801: delete duplicate active indexes

src/VirtoCommerce.ElasticSearchModule.Data/ElasticSearchProvider.cs, tests/VirtoCommerce.ElasticSearchModule.Tests/ElasticSearchTests.cs
https://virtocommerce.atlassian.net/browse/PT-11694
=> PT-11694: rewrite index swap to atomic operation

src/VirtoCommerce.ElasticSearchModule.Data/ElasticSearchProvider.cs, src/VirtoCommerce.ElasticSearchModule.Data/VirtoCommerce.ElasticSearchModule.Data.csproj, src/VirtoCommerce.ElasticSearchModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/PT-11860
=> PT-11860: add suggestions

.editorconfig, Directory.Build.props, VirtoCommerce.ElasticSearchModule.sln.DotSettings, src/VirtoCommerce.ElasticSearchModule.Data/ElasticSearchProvider.cs, src/VirtoCommerce.ElasticSearchModule.Data/Extensions/PropertyExtensions.cs, src/VirtoCommerce.ElasticSearchModule.Data/VirtoCommerce.ElasticSearchModule.Data.csproj, src/VirtoCommerce.ElasticSearchModule.Web/module.manifest, tests/VirtoCommerce.ElasticSearchModule.Tests/PropertyConverterTests.cs, tests/VirtoCommerce.ElasticSearchModule.Tests/SearchProviderTests.cs, tests/VirtoCommerce.ElasticSearchModule.Tests/SearchProviderTestsBase.cs
https://virtocommerce.atlassian.net/browse/PT-11306
=> PT-11306: Implement ISupportIndexCreate

src/VirtoCommerce.ElasticSearchModule.Data/ModuleConstants.cs, src/VirtoCommerce.ElasticSearchModule.Data/VirtoCommerce.ElasticSearchModule.Data.csproj, src/VirtoCommerce.ElasticSearchModule.Web/Module.cs, src/VirtoCommerce.ElasticSearchModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/PT-14556
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ElasticSearch_3.402.0-pr-56-5483.zip
=> PT-14556: Fix search provider registration

Directory.Build.props, src/VirtoCommerce.ElasticSearchModule.Data/VirtoCommerce.ElasticSearchModule.Data.csproj, src/VirtoCommerce.ElasticSearchModule.Web/VirtoCommerce.ElasticSearchModule.Web.csproj, src/VirtoCommerce.ElasticSearchModule.Web/module.manifest, tests/VirtoCommerce.ElasticSearchModule.Tests/VirtoCommerce.ElasticSearchModule.Tests.csproj
https://virtocommerce.atlassian.net/browse/PT-14740
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ElasticSearch_3.800.0-pr-58-56af.zip
=> PT-14740: .net 8

src/VirtoCommerce.ElasticSearchModule.Data/ElasticSearchResponseBuilder.cs
https://virtocommerce.atlassian.net/browse/VCST-960
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ElasticSearch_3.801.0-pr-59-dc89.zip
=> VCST-960: return parsed string in term aggregation result

src/VirtoCommerce.ElasticSearchModule.Data/ElasticSearchResponseBuilder.cs, src/VirtoCommerce.ElasticSearchModule.Data/VirtoCommerce.ElasticSearchModule.Data.csproj, src/VirtoCommerce.ElasticSearchModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VCST-1454
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ElasticSearch_3.802.0-pr-60-ba49.zip
=> VCST-1454: map relevance score to search document
